networks:
  connection-network:
    driver: bridge

#volumes:
#  mongodb_workout_plan_data:
#  mysql_nutrition_data:
#  mongodb_user_data:
  
services:
  mongo-workout-plan:
    image: mongo:latest
    ports:
      - "27017:27017"
#    volumes:
#      - mongodb_workout_plan_data:/data/db
    networks:
      - connection-network

  mongo-user:
    image: mongo:latest
    ports:
      - "27018:27017"
#    volumes:
#      - mongodb_user_data:/data/db
    networks:
      - connection-network
      
  mysql-nutrition:
    image: mysql:latest
#    volumes:
#      - mysql_nutrition_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nutridb
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - connection-network

  
  nutrition-service:
    restart: on-failure
    depends_on:
      - mysql-nutrition
      - user-service
    ports:
      - "8082:8082"
    image: yarin123/nutrition-service
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: 1234
      MYSQL_DB_HOST: mysql-nutrition
      MYSQL_DB_PORT: 3306
      MYSQL_DATABASE: nutridb

    networks:
      - connection-network
  
  workout-plan-service:
    depends_on:
      - mongo-workout-plan
      - user-service
    image: yarin123/workout-plan-service
    ports:
      - "8081:8081"
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-workout-plan
    networks:
      - connection-network

  user-service:
    depends_on:
      - mongo-user
    image: yarin123/user-service
    ports:
      - "8084:8084"
    environment:
      MONGODB_PORT: 27018
      MONGODB_HOST: mongo-user
    networks:
      - connection-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - connection-network

  api-gateway-service:
    depends_on:
      - workout-plan-service
      - nutrition-service
      - user-service
    image: yarin123/api-gateway-service
    ports:
      - "8083:8083"
    environment:
      WORKOUT_PLAN_SERVICE_BASEURL: workout-plan-service:8081
      NUTRITION_SERVICE_BASEURL: nutrition-service:8082
      USER_SERVICE_BASEURL: user-service:8084
    networks:
      - connection-network

