#server:
#  port: 8083

logging:
  level:
    root: TRACE
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: TRACE
    reactor.netty: TRACE

spring:
  cloud:
    gateway:
      routes:
        - id: workout-plan-service
          uri: http://${WORKOUT_PLAN_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Method=GET
            - Path=/workout
          filters:
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 10
#                redis-rate-limiter.burstCapacity: 20
#                redis-rate-limiter.requestedTokens: 1
            - SetPath=/api/workout/all
