#server:
#  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  cloud:
    gateway:
      routes:
        - id: workout-plan-service
          uri: http://${WORKOUT_PLAN_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/ede/workout
          filters:
            - SetPath=/api/workout/all