server:
  port: 8084

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  cloud:
    gateway:
      routes:
        - id: workout-plan-service-a
          uri: http://${WORKOUT_PLAN_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Method=GET
            - Path=/workout
          filters:
            - SetPath=/api/workout
        - id: workout-plan-service-b
          uri: http://${WORKOUT_PLAN_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Method=GET
            - Path=/workout/{id}
          filters:
            - SetPath=/api/workout/{id}
