server:
  port: 8084

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE


spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
          
  cloud:
    gateway:
      routes:
        # Get all workouts
        - id: workout-plan-service-all
          uri: http://${WORKOUT_PLAN_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Method=GET
            - Path=/workout
          filters:
            - SetPath=/api/workout/all

        # Get workout by id
        - id: workout-plan-service-get-id
          uri: http://${WORKOUT_PLAN_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Method=GET
            - Path=/workout/{id}
          filters:
            - SetPath=/api/workout/{id}
        # Create workout
        - id: workout-plan-service-create
          uri: http://${WORKOUT_PLAN_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Method=POST
            - Path=/workout
          filters:
            - SetPath=/api/workout
        # Update workout
        - id: workout-plan-service-update
          uri: http://${WORKOUT_PLAN_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Method=PUT
            - Path=/workout
          filters:
            - SetPath=/api/workout


