#server:
#  port: 8083

logging:
  level:
    root: TRACE
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: TRACE
    reactor.netty: TRACE

spring:
  cloud:
    gateway:
      routes:
        - id: workout-plan-service-a
          uri: http://workout-plan-service:8081
          predicates:
            - Method=GET
            - Path=/workout
          filters:
            - SetPath=/api/workout
        - id: workout-plan-service-b
          uri: http://workout-plan-service:8081
          predicates:
            - Method=GET
            - Path=/workout/{id}
          filters:
            - SetPath=/api/workout/{id}
