server:
  port: 8084

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE


spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  cloud:
    gateway:
      routes:
        - id: workout-plan-service-test
          uri: http://${WORKOUT_PLAN_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Method=GET
            - Path=/test
          filters:
            - SetPath=/api/workout/test
#            - name: RequestRateLimiter
#              args:
#                redis-rate-limiter.replenishRate: 1
#                redis-rate-limiter.burstCapacity: 1
#                redis-rate-limiter.requestedToken: 1
        # WORKOUT SERVICE
        # Get all workouts
        - id: workout-plan-service-all
          uri: http://${WORKOUT_PLAN_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Method=GET
            - Path=/workouts
          filters:
            - SetPath=/api/workout/all
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 6
                redis-rate-limiter.requestedToken: 1
        # Get workout by id
        - id: workout-plan-service-get-id
          uri: http://${WORKOUT_PLAN_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Method=GET
            - Path=/workouts/{id}
          filters:
            - SetPath=/api/workout/{id}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 6
                redis-rate-limiter.requestedToken: 1
        # Create workout
        - id: workout-plan-service-create
          uri: http://${WORKOUT_PLAN_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Method=POST
            - Path=/workouts/
          filters:
            - SetPath=/api/workout/
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 6
                redis-rate-limiter.requestedToken: 1
        # Update workout
        - id: workout-plan-service-update
          uri: http://${WORKOUT_PLAN_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Method=PUT
            - Path=/workouts/{id}
          filters:
            - SetPath=/api/workout/{id}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 6
                redis-rate-limiter.requestedToken: 1
        # Delete workout
        - id: workout-plan-service-delete
          uri: http://${WORKOUT_PLAN_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Method=DELETE
            - Path=/workouts/{id}
          filters:
            - SetPath=/api/workout/{id}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 6
                redis-rate-limiter.requestedToken: 1
        - id: workout-plan-service-get-from-user
          uri: http://${WORKOUT_PLAN_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Method=GET
            - Path=/workouts/user
          filters:
            - SetPath=/api/workout/user
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 6
                redis-rate-limiter.requestedToken: 1
        # NUTRITION SERVICE
        # Get all meals
        - id: nutrition-service-all
          uri: http://${NUTRITION_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Method=GET
            - Path=/meals
          filters:
            - SetPath=/api/meal/all
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 6
                redis-rate-limiter.requestedToken: 1
        # Get meal by id
        - id: nutrition-service-get-id
          uri: http://${NUTRITION_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Method=GET
            - Path=/meals/{id}
          filters:
            - SetPath=/api/meal/{id}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 6
                redis-rate-limiter.requestedToken: 1
        # Create meal
        - id: nutrition-service-create
          uri: http://${NUTRITION_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Method=POST
            - Path=/meals
          filters:
            - SetPath=/api/meal
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 6
                redis-rate-limiter.requestedToken: 1
        # Update meal
        - id: nutrition-service-update
          uri: http://${NUTRITION_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Method=PUT
            - Path=/meals/{id}
          filters:
            - SetPath=/api/meal/{id}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 6
                redis-rate-limiter.requestedToken: 1
        # Delete Meal
        - id: nutrition-service-delete
          uri: http://${NUTRITION_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Method=DELETE
            - Path=/meals/{id}
          filters:
            - SetPath=/api/meal/{id}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 6
                redis-rate-limiter.requestedToken: 1
        - id: nutrition-service-get-from-user
          uri: http://${NUTRITION_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Method=GET
            - Path=/meals/user
          filters:
            - SetPath=/api/meal/user
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 6
                redis-rate-limiter.requestedToken: 1
        # USER SERVICE
        # Get all users
        - id: user-service-all
          uri: http://${USER_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Method=GET
            - Path=/users
          filters:
            - SetPath=/api/user/all
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 6
                redis-rate-limiter.requestedToken: 1
        # Get user by id
        - id: user-service-get-id
          uri: http://${USER_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Method=GET
            - Path=/users/{id}
          filters:
            - SetPath=/api/user/{id}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 6
                redis-rate-limiter.requestedToken: 1
        # Create user
        - id: user-service-create
          uri: http://${USER_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Method=POST
            - Path=/users
          filters:
            - SetPath=/api/user
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 6
                redis-rate-limiter.requestedToken: 1
        # Update user
        - id: user-service-update
          uri: http://${USER_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Method=PUT
            - Path=/users/{id}
          filters:
            - SetPath=/api/user/{id}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 6
                redis-rate-limiter.requestedToken: 1
        # Delete user
        - id: user-service-delete
          uri: http://${USER_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Method=DELETE
            - Path=/users/{id}
          filters:
            - SetPath=/api/user/{id}
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 6
                redis-rate-limiter.requestedToken: 1
